# Generated by Django 5.2.4 on 2025-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('recruiter_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
