# Generated by Django 5.2.4 on 2025-07-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_internship_focus_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='internship_focus_area',
        ),
    ]
