# Generated by Django 5.2.4 on 2025-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_seeking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='registered_with_overseer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='seeking_job',
            field=models.BooleanField(default=True),
        ),
    ]
