# Generated by Django 5.2.4 on 2025-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_is_seeking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='can_university_view',
            field=models.BooleanField(default=True),
        ),
    ]
