# Generated by Django 5.2.4 on 2025-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_candidate_can_university_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
