# Generated by Django 5.2.1 on 2025-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidate_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
