# Generated by Django 5.2.4 on 2025-08-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_resume_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='duration_of_internship',
        ),
    ]
