# Generated by Django 5.2.4 on 2025-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_remove_candidate_duration_of_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='duration_of_internship',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
