# Generated by Django 5.2.4 on 2025-08-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_candidate_duration_of_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='duration_of_internship',
        ),
    ]
