# Generated by Django 5.2.4 on 2025-08-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_remove_candidate_duration_of_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
    ]
