# Generated by Django 5.2.4 on 2025-07-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0008_rename_skills_jobpost_required_skills_and_more'),
        ('candidates', '0005_candidate_internship_focus_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_area_match', models.BooleanField(default=False)),
                ('skill_match_score', models.FloatField(default=0.0)),
                ('degree_match', models.BooleanField(default=False)),
                ('location_match', models.BooleanField(default=False)),
                ('duration_match', models.BooleanField(default=False)),
                ('has_resume', models.BooleanField(default=False)),
                ('total_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.jobpost')),
            ],
            options={
                'unique_together': {('candidate', 'job_post')},
            },
        ),
    ]
