# Generated by Django 5.2.4 on 2025-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatejobmatch',
            options={'ordering': ['-total_score']},
        ),
        migrations.RenameField(
            model_name='candidatejobmatch',
            old_name='focus_area_match',
            new_name='industry_match',
        ),
        migrations.AddField(
            model_name='candidatejobmatch',
            name='professional_title_match',
            field=models.BooleanField(default=False),
        ),
    ]
