# Generated by Django 5.2.1 on 2025-06-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
