# Generated by Django 5.2.4 on 2025-07-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='recruiters.recruiter'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.jobpost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.salary'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job_post')},
        ),
    ]
