# Generated by Django 5.2.4 on 2025-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='duration_of_internship',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
