# Generated by Django 5.2.4 on 2025-07-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobpost_duration_of_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='duration_of_internship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='applications.salary'),
        ),
    ]
