# Generated by Django 5.2.4 on 2025-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_jobpost_duration_of_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='number_of_slots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
