# Generated by Django 5.2.4 on 2025-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_jobpost_number_of_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='skills',
            new_name='required_skills',
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='industry',
            field=models.CharField(default='Tech', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='duration_of_internship',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
