# Generated by Django 4.2.23 on 2025-07-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_rename_skills_jobpost_required_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='duration_of_internship',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
