# Generated by Django 5.2.4 on 2025-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_jobpost_duration_of_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='duration_of_internship',
            field=models.PositiveIntegerField(),
        ),
    ]
