# Generated by Django 5.2.4 on 2025-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_duration_of_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_response',
            field=models.CharField(choices=[('none', 'None'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='none', max_length=20),
        ),
    ]
