# Generated by Django 5.2.4 on 2025-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_application_offer_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
